version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: node.dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app